import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Button from '../components/elements/Button';
import Checkbox from '../components/elements/Checkbox';

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome Avip
        </h1>
        { 
          // Imported Components put below ya /
        }
      </main>
    </div>
  )
}
